ios/Flutter/Debug.xcconfig, ios/Flutter/Release.xcconfig, ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner.xcworkspace/contents.xcworkspacedata, lib/pages/video_viewer_page.dart, lib/pages/webm_viewer_page.dart, lib/widgets/controls_overlay_widget.dart, lib/widgets/post_widget.dart, lib/widgets/vlc_player_with_controls_widget.dart, pubspec.lock, pubspec.yaml
Uses VLC for webM support. This is the only possible library out there that will have support. I worked on Flutter VLC so I'm very familiar with it.
I took the player and its controls from the VLC sample project. Feel free to modify at your own will. Pull down this code and see what's available, you may find the feature set beneficial or not. Upto you.
Make sure you run Flutter Pub Get to pull down new dependency.
=> Webm support for iOS. Leverages VLC Player.

ios/Podfile.lock, lib/main.dart, lib/pages/board_page.dart, lib/pages/boards_list_page.dart, lib/pages/gallery_page.dart, lib/pages/history_page.dart, lib/pages/image_viewer_page.dart, lib/pages/replies_page.dart, lib/pages/settings_page.dart, lib/pages/thread_page.dart, lib/pages/video_viewer_page.dart, lib/pages/view_photo.dart, lib/pages/webm_viewer_page.dart, pubspec.lock, pubspec.yaml
Originally requested by @mitchross, adds a gallery view to threads. Webms are todo.
=> Gallery view

ios/Flutter/AppFrameworkInfo.plist, ios/Podfile, ios/Podfile.lock, pubspec.lock, pubspec.yaml
Few package upgrades to fix ios from not running. Fixes podfile too.
=> fix ios from not building/running

lib/pages/board_page.dart
=> Removed board code from app bar title for narrow screens

android/app/build.gradle, lib/pages/webm_viewer_page.dart, lib/widgets/video_player_widget/video_player_widget.dart, pubspec.lock, pubspec.yaml
Updated Packages
Fixed Package Permission Issue that caused build to fail
Fix VLC widget back button issues.
=> Webm player back button crashes

lib/dependency_injector.dart, lib/widgets/form_widget/form_widget.dart, packages/mobichan_data/lib/src/features/board/datasources/remote_datasource.dart, packages/mobichan_data/lib/src/features/captcha/datasources/remote_datasource.dart, packages/mobichan_data/lib/src/features/post/datasources/remote_datasource.dart, packages/mobichan_data/lib/src/features/release/datasources/remote_datasource.dart
=> Swapped http.Client with Dio in remote datasources

lib/features/post/view/thread_page/builders.dart, lib/features/post/view/thread_page/handlers.dart, lib/features/post/widgets/reply_widget/builders.dart, lib/features/post/widgets/thread_widget/builders.dart, lib/features/post/widgets/thread_widget/handlers.dart, lib/features/post/widgets/thread_widget/widget.dart, packages/mobichan_domain/lib/src/features/post/entities/post.dart
=> Tapping a thread opens the carousel on image 0

lib/features/post/view/thread_page/builders.dart, lib/features/post/view/thread_page/handlers.dart, lib/features/post/view/thread_page/page.dart, pubspec.lock, pubspec.yaml
=> Fixed the scroll to top/bottom delay issue

lib/features/post/cubits/replies_cubit/replies_cubit.dart, lib/features/post/cubits/threads_cubit/threads_cubit.dart, lib/features/post/view/threads_page/builders.dart, lib/features/post/view/threads_page/handlers.dart, lib/features/post/widgets/form_widget/handlers.dart, lib/features/post/widgets/form_widget/widget.dart
=> Fixed form dropdown not dismissing when post is successful

lib/core/cubits/post_form_cubit/post_form_cubit.dart
=> Fixed slow comment textfield

lib/core/cubits/post_form_cubit/post_form_cubit.dart, lib/features/post/widgets/form_widget/builders.dart, lib/features/post/widgets/form_widget/handlers.dart, lib/features/post/widgets/form_widget/widget.dart
=> Clearing fields on successful posts + textfields styling

lib/features/board/widgets/board_drawer/handlers.dart
=> Fixed board drawer favorite button not refreshing favorites

lib/app.dart, lib/constants.dart, lib/core/widgets/snackbars/success_snackbar.dart, lib/features/captcha/widgets/captcha_slider_widget.dart, lib/features/post/cubits/replies_dialog_cubit/replies_dialog_cubit.dart, lib/features/post/cubits/replies_dialog_cubit/replies_dialog_state.dart, lib/features/post/view/replies_page/handlers.dart, lib/features/post/view/replies_page/page.dart, lib/features/post/widgets/content_widget/handlers.dart, lib/features/post/widgets/content_widget/widget.dart, lib/features/post/widgets/reply_widget/handlers.dart, lib/features/post/widgets/reply_widget/widget.dart, lib/features/post/widgets/thread_widget/builders.dart
=> Added highlighted quotelinks in replies dialog

lib/features/board/widgets/board_tabs.dart
=> Fixed tab switching not updating favorites button

lib/features/board/view/board_nsfw_check_page/page.dart, lib/features/board/view/board_page/page.dart, lib/features/board/widgets/board_drawer/builders.dart, lib/features/post/cubits/history_cubit/history_cubit.dart
=> Fixed provider errors and history search

assets/translations/en-US.json, assets/translations/fr-FR.json, lib/core/widgets/setting_provider.dart, lib/features/post/view/webm_viewer_page/page.dart, lib/features/post/widgets/video_player_widget/widget.dart, packages/mobichan_data/lib/src/features/settings/datasources/local_datasource.dart, pubspec.lock, pubspec.yaml
=> Added mute by default setting

lib/features/post/widgets/video_player_controls_widget/widget.dart
Fix Video Overlay. Remove overlay.
=> Fix video overlay

assets/translations/en-US.json, assets/translations/fr-FR.json, lib/features/post/widgets/date_widget/date_widget.dart, lib/features/post/widgets/date_widget/widget.dart, lib/features/post/widgets/reply_widget/builders.dart, lib/features/post/widgets/reply_widget/widget.dart, lib/features/post/widgets/thread_widget/builders.dart, lib/features/post/widgets/widgets.dart, lib/main.dart, packages/mobichan_data/lib/src/features/settings/models/setting_model.dart, packages/mobichan_data/pubspec.lock, packages/mobichan_domain/pubspec.lock, pubspec.lock, pubspec.yaml
=> Added dates with a setting for different formats

lib/features/post/view/thread_page/builders.dart, lib/features/post/view/thread_page/page.dart, lib/features/post/widgets/reply_widget/builders.dart, packages/mobichan_domain/lib/src/features/post/entities/entities.dart, packages/mobichan_domain/lib/src/features/post/entities/post_with_depth.dart
=> Fixed grey void issue in flag boards

ios/Podfile.lock, lib/core/cubits/post_form_cubit/post_form_cubit.dart, lib/core/cubits/post_form_cubit/post_form_state.dart, lib/features/post/cubits/replies_cubit/replies_cubit.dart, lib/features/post/cubits/threads_cubit/threads_cubit.dart, lib/features/post/widgets/form_widget/builders.dart, lib/features/post/widgets/form_widget/handlers.dart, packages/mobichan_data/lib/src/features/post/datasources/remote_datasource.dart, packages/mobichan_data/lib/src/features/post/repositories/repository_impl.dart, packages/mobichan_domain/lib/src/features/post/repositories/repository.dart, pubspec.lock, pubspec.yaml
=> Fixed filename being replaced by image_picker

android/app/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, assets/translations/en-US.json, ios/Podfile.lock, lib/core/extensions/device_info_extension.dart, lib/features/board/widgets/board_expansion_tile/widget.dart, lib/features/post/widgets/image_widget/builders.dart, lib/features/post/widgets/image_widget/widget.dart, macos/Flutter/GeneratedPluginRegistrant.swift, packages/mobichan_data/lib/src/features/settings/models/setting_model.dart, packages/mobichan_data/pubspec.lock, packages/mobichan_domain/pubspec.lock, pubspec.lock, pubspec.yaml
@Rukkaitto 
Found a way to instantly update. Cleaner code. Simplier. Closed other PR for this one.
=> Center crop image setting
